# Generated by Django 3.2.19 on 2023-05-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='oder',
            new_name='order',
        ),
    ]
