# Generated by Django 3.2.19 on 2023-05-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_oder_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='customer',
            name='cash_available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='lname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
