# Generated by Django 3.2.19 on 2023-05-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_customer_cash_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cash_available',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('points', 'Points')], default='cash', max_length=10),
        ),
    ]
